# Generated by Django 5.2.14 on 2026-05-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
